export const allData = {
  count: 10,
  next: '냥',
  previous: '멍',
  results: [
    {
      id: 1,
      user_id: 0,
      type_display: '이건뭐지',
      content: '/mypage',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 2,
      user_id: 0,
      type_display: '이건뭐지',
      content: '/email-find',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/email-find',
      user: 0,
    },
    {
      id: 3,
      user_id: 0,
      type_display: '이건뭐지',
      content: 'password-find',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/password-find',
      user: 0,
    },
    {
      id: 4,
      user_id: 0,
      type_display: '이건뭐지',
      content: 'login',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/login',
      user: 0,
    },
    {
      id: 5,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 6,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 7,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 8,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 9,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 10,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
  ],
}

export const chatData = {
  status: 'success',
  code: 'SUCCESS',
  message: '메시지 목록 조회 성공',
  data: {
    messages: [
      {
        id: 5,
        sender_id: 5,
        sender_nickname: '홍길동',
        study_group_id: 20,
        study_group_name: 'Python 데이터 분석 스터디',
        content: '채팅더미.',
        file_url: null,
        is_read: true,
        created_at: '2025-10-15T10:30:00Z',
      },
      {
        id: 4,
        sender_id: 5,
        sender_nickname: '김민섭',
        study_group_id: 10,
        study_group_name: '안냐아ㅏㅏㅏㅏ아ㅏㅇ아아아아아ㅏ아옹',
        content: '안녕하세요.',
        file_url: null,
        is_read: false,
        created_at: '2025-10-15T10:30:00Z',
      },
      {
        id: 3,
        sender_id: 5,
        sender_nickname: '민현서',
        study_group_id: 30,
        study_group_name: 'AWS 클라우드 아키텍처 스터디',
        content: '채팅방 더미데이터입니다.',
        file_url: null,
        is_read: false,
        created_at: '2025-10-15T10:30:00Z',
      },
      {
        id: 2,
        sender_id: 5,
        sender_nickname: '정승윤',
        study_group_id: 40,
        study_group_name: 'Node.js 백엔드 개발팀',
        content: '안니용',
        file_url: null,
        is_read: true,
        created_at: '2025-10-15T10:30:00Z',
      },
      {
        id: 1,
        sender_id: 5,
        sender_nickname: '김미진',
        study_group_id: 50,
        study_group_name: '메롱',
        content: '긋쵸',
        file_url: null,
        is_read: true,
        created_at: '2025-10-15T10:30:00Z',
      },
      {
        id: 0,
        sender_id: 5,
        sender_nickname: '김현진',
        study_group_id: 60,
        study_group_name: '얏호',
        content: '응애',
        file_url: null,
        is_read: true,
        created_at: '2025-10-15T10:30:00Z',
      },
    ],
    pagination: {
      page: 1,
      page_size: 100,
      total_count: 6,
    },
  },
}
