export const allData = {
  count: 10,
  next: '냥',
  previous: '멍',
  results: [
    {
      id: 1,
      user_id: 0,
      type_display: '이건뭐지',
      content: '/mypage',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 2,
      user_id: 0,
      type_display: '이건뭐지',
      content: '/email-find',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/email-find',
      user: 0,
    },
    {
      id: 3,
      user_id: 0,
      type_display: '이건뭐지',
      content: 'password-find',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/password-find',
      user: 0,
    },
    {
      id: 4,
      user_id: 0,
      type_display: '이건뭐지',
      content: 'login',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/login',
      user: 0,
    },
    {
      id: 5,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 6,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 7,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 8,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 9,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: true,
      back_url_link: '/mypage',
      user: 0,
    },
    {
      id: 10,
      user_id: 0,
      type_display: '이건뭐지',
      content: '알림입니다',
      type: 'APPLICATIONS_CREATED',
      is_read: false,
      back_url_link: '/mypage',
      user: 0,
    },
  ],
}
